version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        # Passe la variable au Dockerfile → VITE_API_BASE_URL
        VITE_API_BASE_URL: http://backend:8000
    ports:
      - "8080:80"
    depends_on:
      - backend
    # Log uniquement pour debug
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Exemple minimal de service backend (FastAPI)
  backend:
    build: ./backend        # si tu crées un dossier backend/
    # image: ghcr.io/your-org/pdf-analyzer:latest   # si déjà publié
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
