services:
  anonymizer:
    build: .
    container_name: anonymizer # nom explicite dans Docker Desktop
    restart: unless-stopped

    environment:
      - LOG_LEVEL=info # niveau de log uvicorn
      - MAX_PAYLOAD_SIZE=51200 # 50 kB max par requête

    ports:
      - "8081:8000" # hôte:conteneur

    deploy:
      # limites ressources (Docker Compose v3.x)
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
